### ISSUE TITLE
autoplay: true 没生效，手动滑动一下才能自动轮播。

### ISSUE THREAD

**Issue by xuyawen** [lianyagang/flutter_swiper_null_safety#1]
Swiper(
  autoplay: true,
  scrollDirection: Axis.vertical,
  itemBuilder: (BuildContext context, int index) {
    return swiperList[index];
  },
  itemCount: swiperList.length,
)

视图加载之后autoplay没生效，需要手动滑动之后才会生效。

**Comment by lianyagang** [comment]
> Swiper(
> autoplay: true,
> scrollDirection: Axis.vertical,
> itemBuilder: (BuildContext context, int index) {
> return swiperList[index];
> },
> itemCount: swiperList.length,
> )
> 
> 视图加载之后autoplay没生效，需要手动滑动之后才会生效。

已修复，等待pub上传更新1.0.1

**Comment by lianyagang** [comment]
> Swiper(
> autoplay: true,
> scrollDirection: Axis.vertical,
> itemBuilder: (BuildContext context, int index) {
> return swiperList[index];
> },
> itemCount: swiperList.length,
> )
> 
> 视图加载之后autoplay没生效，需要手动滑动之后才会生效。
使用以下这个版本
dependencies:
  flutter_swiper_null_safety: ^1.0.1
