### ISSUE TITLE
在flutter3.0中报错WidgetsBinding.instance!.addPostFrameCallback(_onGetSize);

### ISSUE THREAD

**Issue by joeoops** [lianyagang/flutter_swiper_null_safety#17]

**Comment by shuaiDevelop** [comment]
可以试试我的方法：直接把代码拷一份到自己工程，把相关提示代码 **WidgetsBinding.instance!.**  改为 **WidgetsBinding.instance.**   就没有这个报错了。

**Comment by kyawsanoo** [comment]
Flutter3.0, Warning: Operand of
null-aware operation '!' has type 'WidgetsBinding' which ex
cludes null.

**Comment by lianyagang** [comment]
已修复。重新发包
