### ISSUE TITLE
升能到flutter3.0后提示WidgetsBinding.instance!.addPostFrameCallback(_getSize);

### ISSUE THREAD

**Issue by zengchanghuan** [lianyagang/flutter_swiper_null_safety#18]
升级后提示
    WidgetsBinding.instance!.addPostFrameCallback(_getSize);

**Comment by jeromekai** [comment]
> 升级后提示 WidgetsBinding.instance!.addPostFrameCallback(_getSize);

  flutter_swiper_null_safety_flutter3: ^2.0.0

**Comment by zengchanghuan** [comment]
@jeromekai 可以了，谢谢！
