### ISSUE TITLE
_onGetSize getting called with dirty context

### ISSUE THREAD

**Issue by Mayb3Nots** [lianyagang/flutter_swiper_null_safety#2]
Error at https://github.com/lianyagang/flutter_swiper_null_safety/blob/8429674180985821b2fbffc565fa1362143e7085/lib/src/transformer_page_view/transformer_page_view.dart#L442-L451

```
I/flutter (26103): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (26103): The following assertion was thrown during a scheduler callback:
I/flutter (26103): This widget has been unmounted, so the State no longer has a context (and should be considered
I/flutter (26103): defunct).
I/flutter (26103): Consider canceling any active work during "dispose" or using the "mounted" getter to determine if
I/flutter (26103): the State is still active.
I/flutter (26103):
I/flutter (26103): When the exception was thrown, this was the stack:
I/flutter (26103): #0      State.context.<anonymous closure>
package:flutter/…/widgets/framework.dart:1088
I/flutter (26103): #1      State.context
package:flutter/…/widgets/framework.dart:1094
I/flutter (26103): #2      _TransformerPageViewState._onGetSize
package:flutter_swiper_null_safety/…/transformer_page_view/transformer_page_view.dart:444
I/flutter (26103): #3      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
I/flutter (26103): #4      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1090
I/flutter (26103): #5      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:998
I/flutter (26103): #9      _invoke (dart:ui/hooks.dart:161:10)
I/flutter (26103): #10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
I/flutter (26103): #11     _drawFrame (dart:ui/hooks.dart:120:31)
I/flutter (26103): (elided 3 frames from dart:async)
I/flutter (26103): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by lianyagang** [comment]
> Error at
> 
> https://github.com/lianyagang/flutter_swiper_null_safety/blob/8429674180985821b2fbffc565fa1362143e7085/lib/src/transformer_page_view/transformer_page_view.dart#L442-L451
> 
> ```
> I/flutter (26103): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
> I/flutter (26103): The following assertion was thrown during a scheduler callback:
> I/flutter (26103): This widget has been unmounted, so the State no longer has a context (and should be considered
> I/flutter (26103): defunct).
> I/flutter (26103): Consider canceling any active work during "dispose" or using the "mounted" getter to determine if
> I/flutter (26103): the State is still active.
> I/flutter (26103):
> I/flutter (26103): When the exception was thrown, this was the stack:
> I/flutter (26103): #0      State.context.<anonymous closure>
> package:flutter/…/widgets/framework.dart:1088
> I/flutter (26103): #1      State.context
> package:flutter/…/widgets/framework.dart:1094
> I/flutter (26103): #2      _TransformerPageViewState._onGetSize
> package:flutter_swiper_null_safety/…/transformer_page_view/transformer_page_view.dart:444
> I/flutter (26103): #3      SchedulerBinding._invokeFrameCallback
> package:flutter/…/scheduler/binding.dart:1144
> I/flutter (26103): #4      SchedulerBinding.handleDrawFrame
> package:flutter/…/scheduler/binding.dart:1090
> I/flutter (26103): #5      SchedulerBinding._handleDrawFrame
> package:flutter/…/scheduler/binding.dart:998
> I/flutter (26103): #9      _invoke (dart:ui/hooks.dart:161:10)
> I/flutter (26103): #10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
> I/flutter (26103): #11     _drawFrame (dart:ui/hooks.dart:120:31)
> I/flutter (26103): (elided 3 frames from dart:async)
> I/flutter (26103): ════════════════════════════════════════════════════════════════════════════════════════════════════
> ```

How do you used it

**Comment by lianyagang** [comment]
> > https://github.com/best-flutter/transformer_page_view/pull/44/files?file-filters%5B%5D=.dart&file-filters%5B%5D=.lock&file-filters%5B%5D=.xml#diff-f64f550d7c7db79c0d5219784f2ca3cdc4edaf4fac44fe65cd01bd5ed2062fb6
> 
> i will try it ,but i can't reproduce this issue
> and i push something code u can try it

if it work for u ,please tell me ,i will publish to pub.dev and upgrade version

**Comment by Mayb3Nots** [comment]
> > > https://github.com/best-flutter/transformer_page_view/pull/44/files?file-filters%5B%5D=.dart&file-filters%5B%5D=.lock&file-filters%5B%5D=.xml#diff-f64f550d7c7db79c0d5219784f2ca3cdc4edaf4fac44fe65cd01bd5ed2062fb6
> > 
> > 
> > i will try it ,but i can't reproduce this issue
> > and i push something code u can try it
> 
> if it work for u ,please tell me ,i will publish to pub.dev and upgrade version

Hi I can confirm that the lastest commit fixed my issue. Thanks
